[package]
name = "audio-fun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alto = "3.0.4"
cpal = "0.14.2"
rodio = "0.16.0"
